-- Optional cleanup guide: old experimental Supabase tables that do not match Google Sheet tab names.
-- IMPORTANT: All DROP commands are commented out on purpose.
-- Do not uncomment/run these lines unless you have already confirmed the data is no longer needed
-- or has already been synced into the exact Sheet-name tables.
--
-- Current Sheet-name tables that should be kept:
-- "Employees", "Checkins", "Leaves", "OT", "Payments", "LeaveQuota",
-- "PayItems", "Holidays", "Config", "Logs", "Approvers"
--
-- If you accidentally dropped tables but Google Sheets still has data:
-- 1) Run supabase/structured-schema.sql again.
-- 2) In Apps Script, run syncSupabaseStructuredFromSheets().
-- 3) Run testSupabaseStructuredCounts() to verify row counts.

-- Old experimental tables from the first Supabase draft:
-- drop table if exists public.employees cascade;
-- drop table if exists public.leave_requests cascade;
-- drop table if exists public.ot_requests cascade;
-- drop table if exists public.attendance_logs cascade;
-- drop table if exists public.sync_errors cascade;
-- drop table if exists public.app_rows cascade;

-- Older structured table names from the first draft:
-- drop table if exists public.employees_sheet cascade;
-- drop table if exists public.checkins_sheet cascade;
-- drop table if exists public.leaves_sheet cascade;
-- drop table if exists public.ot_sheet cascade;
-- drop table if exists public.payments_sheet cascade;
-- drop table if exists public.leave_quota_sheet cascade;
-- drop table if exists public.pay_items_sheet cascade;
-- drop table if exists public.holidays_sheet cascade;
-- drop table if exists public.config_sheet cascade;
-- drop table if exists public.logs_sheet cascade;
-- drop table if exists public.approvers_sheet cascade;
