-- Structured Supabase schema matching Mini HR Google Sheets.
-- Run this in Supabase SQL Editor before syncSupabaseStructuredFromSheets().

create table if not exists public.employees_sheet (
  employee_id text primary key,
  line_user_id text unique,
  display_name text,
  phone text,
  email text,
  department text,
  position text,
  base_pay_monthly numeric,
  ot_rate_per_hour numeric,
  bank_name text,
  bank_account_no text,
  bank_account_name text,
  selfie_url text,
  id_card_url text,
  approver_l1_id text,
  approver_l2_id text,
  approver_l3_id text,
  role text,
  start_date date,
  is_active boolean,
  registered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.checkins_sheet (
  checkin_id text primary key,
  employee_id text,
  checkin_date date,
  slot text,
  checkin_at timestamptz,
  lat numeric(10, 7),
  lng numeric(10, 7),
  distance_m numeric(10, 2),
  selfie_url text,
  status text,
  approved_by text,
  approved_at timestamptz,
  branch_name text,
  updated_at timestamptz not null default now()
);

create index if not exists checkins_sheet_employee_date_idx
  on public.checkins_sheet (employee_id, checkin_date);

create table if not exists public.leaves_sheet (
  leave_id text primary key,
  employee_id text,
  leave_type text,
  duration_type text,
  start_date date,
  end_date date,
  start_time time,
  end_time time,
  total_days numeric(8, 2),
  total_hours numeric(8, 2),
  reason text,
  evidence_url text,
  status text,
  current_approver text,
  approval_history jsonb,
  submitted_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists leaves_sheet_employee_start_idx
  on public.leaves_sheet (employee_id, start_date);

create index if not exists leaves_sheet_status_idx
  on public.leaves_sheet (status);

create table if not exists public.ot_sheet (
  ot_id text primary key,
  employee_id text,
  ot_date date,
  start_time time,
  end_time time,
  total_hours numeric(8, 2),
  reason text,
  status text,
  current_approver text,
  approval_history jsonb,
  submitted_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists ot_sheet_employee_date_idx
  on public.ot_sheet (employee_id, ot_date);

create index if not exists ot_sheet_status_idx
  on public.ot_sheet (status);

create table if not exists public.payments_sheet (
  payment_id text primary key,
  employee_id text,
  period text,
  work_days numeric(8, 2),
  ot_hours numeric(8, 2),
  base_pay numeric,
  ot_pay numeric,
  bonus numeric,
  deduction numeric,
  total_amount numeric,
  status text,
  closed_at timestamptz,
  paid_at timestamptz,
  note text,
  updated_at timestamptz not null default now()
);

create index if not exists payments_sheet_employee_period_idx
  on public.payments_sheet (employee_id, period);

create table if not exists public.leave_quota_sheet (
  employee_id text not null,
  year integer not null,
  sick_quota numeric(8, 2),
  sick_used numeric(8, 2),
  personal_quota numeric(8, 2),
  personal_used numeric(8, 2),
  vacation_quota numeric(8, 2),
  vacation_used numeric(8, 2),
  updated_at timestamptz not null default now(),
  primary key (employee_id, year)
);

create table if not exists public.pay_items_sheet (
  item_id text primary key,
  employee_id text,
  period text,
  type text,
  amount numeric,
  reason text,
  created_by text,
  created_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.holidays_sheet (
  date date primary key,
  name text,
  type text,
  updated_at timestamptz not null default now()
);

create table if not exists public.config_sheet (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.logs_sheet (
  id bigint generated by default as identity primary key,
  timestamp timestamptz,
  level text,
  function text,
  user_id text,
  message text,
  payload text,
  updated_at timestamptz not null default now()
);

create table if not exists public.approvers_sheet (
  employee_id text not null,
  level text not null,
  approver_id text,
  is_active boolean,
  updated_at timestamptz not null default now(),
  primary key (employee_id, level)
);

alter table public.employees_sheet enable row level security;
alter table public.checkins_sheet enable row level security;
alter table public.leaves_sheet enable row level security;
alter table public.ot_sheet enable row level security;
alter table public.payments_sheet enable row level security;
alter table public.leave_quota_sheet enable row level security;
alter table public.pay_items_sheet enable row level security;
alter table public.holidays_sheet enable row level security;
alter table public.config_sheet enable row level security;
alter table public.logs_sheet enable row level security;
alter table public.approvers_sheet enable row level security;

