-- Structured Supabase schema matching Mini HR Google Sheets.
-- Table names intentionally match Google Sheet tab names exactly.
-- Run this in Supabase SQL Editor before syncSupabaseStructuredFromSheets().

create table if not exists public."Employees" (
  employee_id text primary key,
  line_user_id text unique,
  display_name text,
  phone text,
  email text,
  department text,
  position text,
  base_pay_monthly numeric,
  ot_rate_per_hour numeric,
  bank_name text,
  bank_account_no text,
  bank_account_name text,
  selfie_url text,
  id_card_url text,
  approver_l1_id text,
  approver_l2_id text,
  approver_l3_id text,
  role text,
  start_date date,
  is_active boolean,
  registered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public."Checkins" (
  checkin_id text primary key,
  employee_id text,
  checkin_date date,
  slot text,
  checkin_at timestamptz,
  lat numeric(10, 7),
  lng numeric(10, 7),
  distance_m numeric(10, 2),
  selfie_url text,
  status text,
  approved_by text,
  approved_at timestamptz,
  branch_name text,
  updated_at timestamptz not null default now()
);

create index if not exists checkins_employee_date_idx
  on public."Checkins" (employee_id, checkin_date);

create table if not exists public."Leaves" (
  leave_id text primary key,
  employee_id text,
  leave_type text,
  duration_type text,
  start_date date,
  end_date date,
  start_time time,
  end_time time,
  total_days numeric(8, 2),
  total_hours numeric(8, 2),
  reason text,
  evidence_url text,
  status text,
  current_approver text,
  approval_history jsonb,
  submitted_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists leaves_employee_start_idx
  on public."Leaves" (employee_id, start_date);

create index if not exists leaves_status_idx
  on public."Leaves" (status);

create table if not exists public."OT" (
  ot_id text primary key,
  employee_id text,
  ot_date date,
  start_time time,
  end_time time,
  total_hours numeric(8, 2),
  reason text,
  status text,
  current_approver text,
  approval_history jsonb,
  submitted_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists ot_employee_date_idx
  on public."OT" (employee_id, ot_date);

create index if not exists ot_status_idx
  on public."OT" (status);

create table if not exists public."Payments" (
  payment_id text primary key,
  employee_id text,
  period text,
  work_days numeric(8, 2),
  ot_hours numeric(8, 2),
  base_pay numeric,
  ot_pay numeric,
  bonus numeric,
  deduction numeric,
  total_amount numeric,
  status text,
  closed_at timestamptz,
  paid_at timestamptz,
  note text,
  updated_at timestamptz not null default now()
);

create index if not exists payments_employee_period_idx
  on public."Payments" (employee_id, period);

create table if not exists public."LeaveQuota" (
  employee_id text not null,
  year integer not null,
  sick_quota numeric(8, 2),
  sick_used numeric(8, 2),
  personal_quota numeric(8, 2),
  personal_used numeric(8, 2),
  vacation_quota numeric(8, 2),
  vacation_used numeric(8, 2),
  updated_at timestamptz not null default now(),
  primary key (employee_id, year)
);

create table if not exists public."PayItems" (
  item_id text primary key,
  employee_id text,
  period text,
  type text,
  amount numeric,
  reason text,
  created_by text,
  created_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public."Holidays" (
  date date primary key,
  name text,
  type text,
  updated_at timestamptz not null default now()
);

create table if not exists public."Config" (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists public."Logs" (
  id bigint generated by default as identity primary key,
  timestamp timestamptz,
  level text,
  function text,
  user_id text,
  message text,
  payload text,
  updated_at timestamptz not null default now()
);

create table if not exists public."Approvers" (
  employee_id text not null,
  level text not null,
  approver_id text,
  is_active boolean,
  updated_at timestamptz not null default now(),
  primary key (employee_id, level)
);

alter table public."Employees" enable row level security;
alter table public."Checkins" enable row level security;
alter table public."Leaves" enable row level security;
alter table public."OT" enable row level security;
alter table public."Payments" enable row level security;
alter table public."LeaveQuota" enable row level security;
alter table public."PayItems" enable row level security;
alter table public."Holidays" enable row level security;
alter table public."Config" enable row level security;
alter table public."Logs" enable row level security;
alter table public."Approvers" enable row level security;
